[Unit]
After=router-network-ready.target
Wants=router-network-ready.target
Before=hostapd.service kea-dhcp4.service unbound.service jool.service

[Service]
ExecStartPre=/usr/bin/test -r /etc/nftables.conf
